import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import {getFirestore,doc,getDoc,setDoc,collection,addDoc,getDocs,query,orderBy,deleteDoc} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let user,profile={age:31,height:170,weight:73,calGoal:1950,pGoal:140,cGoal:220,fGoal:65,stepGoal:10000},ppl='Push',signup=false,stream;
$('date').textContent=new Date().toLocaleDateString();
const day=()=>new Date().toISOString().slice(0,10),userRef=()=>doc(db,'users',user.uid),dayRef=()=>doc(db,'users',user.uid,'days',day());
function show(id){document.querySelectorAll('.page').forEach(x=>x.hidden=x.id!==id);document.querySelectorAll('nav button').forEach(x=>x.style.background=x.dataset.page===id?'#2563eb':'#172236');if(id==='food')food();if(id==='workout')exercises();if(id==='progress')history();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.dataset.page));
$('toggle').onclick=()=>{signup=!signup;$('authTitle').textContent=signup?'Create account':'Sign in';$('toggle').textContent=signup?'Back to sign in':'Create account'};
$('authForm').onsubmit=async e=>{e.preventDefault();try{if(signup){const c=await createUserWithEmailAndPassword(auth,$('email').value,$('password').value);await setDoc(userRef(),profile)}else await signInWithEmailAndPassword(auth,$('email').value,$('password').value)}catch(e){$('authMsg').textContent=e.message}};
onAuthStateChanged(auth,async u=>{user=u;if(!u){$('auth').hidden=false;$('app').hidden=true;$('logout').hidden=true;return}$('auth').hidden=true;$('app').hidden=false;$('logout').hidden=false;let s=await getDoc(userRef());if(s.exists())profile={...profile,...s.data()};else await setDoc(userRef(),profile);fill();await refresh();show('dash')});
$('logout').onclick=()=>signOut(auth);
function fill(){$('age').value=profile.age;$('height').value=profile.height;$('goalCal').value=profile.calGoal;$('goalP').value=profile.pGoal;$('goalC').value=profile.cGoal;$('goalF').value=profile.fGoal;$('goalSteps').value=profile.stepGoal}
$('settingsForm').onsubmit=async e=>{e.preventDefault();profile={...profile,age:+$('age').value,height:+$('height').value,calGoal:+$('goalCal').value,pGoal:+$('goalP').value,cGoal:+$('goalC').value,fGoal:+$('goalF').value,stepGoal:+$('goalSteps').value};await setDoc(userRef(),profile,{merge:true});await refresh()};
async function getDay(){let s=await getDoc(dayRef());return s.exists()?s.data():{cal:0,p:0,c:0,f:0,steps:0,workout:'Rest'}}async function refresh(){let d=await getDay();$('cal').textContent=Math.round(d.cal);$('calGoal').textContent=profile.calGoal;$('calBar').style.width=Math.min(100,d.cal/profile.calGoal*100)+'%';$('weightDash').textContent=profile.weight;$('stepsDash').textContent=(d.steps||0).toLocaleString();$('workoutDash').textContent=d.workout||'Rest';$('macros').innerHTML=`<div class="row">Protein <b>${Math.round(d.p||0)} / ${profile.pGoal} g</b></div><div class="row">Carbs <b>${Math.round(d.c||0)} / ${profile.cGoal} g</b></div><div class="row">Fat <b>${Math.round(d.f||0)} / ${profile.fGoal} g</b></div>`}
$('foodForm').onsubmit=async e=>{e.preventDefault();let f={name:$('fname').value,serving:$('serving').value,cal:+$('fcal').value,p:+$('fp').value,c:+$('fc').value,f:+$('ff').value};await addDoc(collection(db,'users',user.uid,'days',day(),'foods'),f);let d=await getDay();d.cal+=f.cal;d.p+=f.p;d.c+=f.c;d.f+=f.f;await setDoc(dayRef(),d,{merge:true});e.target.reset();await refresh();food()};
async function food(){let s=await getDocs(query(collection(db,'users',user.uid,'days',day(),'foods'),orderBy('__name__')));$('foodList').innerHTML=s.docs.map(x=>{let f=x.data();return `<div class="row"><span>${f.name}<br><small>${f.serving||''} · ${f.cal} kcal · P ${f.p} C ${f.c} F ${f.f}</small></span><button data-del="${x.id}">Delete</button></div>`}).join('')||'<p>No food logged.</p>';document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{let r=doc(db,'users',user.uid,'days',day(),'foods',b.dataset.del),s=await getDoc(r);if(s.exists()){let f=s.data(),d=await getDay();d.cal-=f.cal;d.p-=f.p;d.c-=f.c;d.f-=f.f;await setDoc(dayRef(),d,{merge:true});await deleteDoc(r);await refresh();food()}})}
document.querySelectorAll('[data-ppl]').forEach(b=>b.onclick=()=>{ppl=b.dataset.ppl});$('exForm').onsubmit=async e=>{e.preventDefault();await addDoc(collection(db,'users',user.uid,'days',day(),'exercises'),{type:ppl,name:$('ename').value,sets:+$('sets').value,reps:+$('reps').value,weight:+$('ew').value});e.target.reset();await exercises()};$('finish').onclick=async()=>{await setDoc(dayRef(),{workout:ppl},{merge:true});await refresh()};
async function exercises(){let s=await getDocs(collection(db,'users',user.uid,'days',day(),'exercises'));$('exList').innerHTML=s.docs.map(x=>{let e=x.data();return `<div class="row"><span>${e.name}<br><small>${e.type} · ${e.sets}×${e.reps} @ ${e.weight} kg</small></span><button data-ex="${x.id}">Delete</button></div>`}).join('')||'<p>No exercises logged.</p>';document.querySelectorAll('[data-ex]').forEach(b=>b.onclick=async()=>{await deleteDoc(doc(db,'users',user.uid,'days',day(),'exercises',b.dataset.ex));exercises()})}
$('weightForm').onsubmit=async e=>{e.preventDefault();profile.weight=+$('weightInput').value;await setDoc(userRef(),profile,{merge:true});await addDoc(collection(db,'users',user.uid,'weights'),{date:day(),weight:profile.weight});await refresh();history()};$('stepsForm').onsubmit=async e=>{e.preventDefault();await setDoc(dayRef(),{steps:+$('stepsInput').value},{merge:true});await refresh()};async function history(){let s=await getDocs(query(collection(db,'users',user.uid,'weights'),orderBy('date','desc')));$('history').innerHTML=s.docs.map(x=>`<div class="row">${x.data().date}<b>${x.data().weight} kg</b></div>`).join('')||'<p>No history.</p>'}
$('scan').onclick=async()=>{if(!('BarcodeDetector'in window)){alert('Barcode scanning is not supported by this browser.');return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});$('video').hidden=false;$('video').srcObject=stream;await $('video').play();let d=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e']});let loop=async()=>{if(!stream)return;let c=await d.detect($('video'));if(c.length){let code=c[0].rawValue;stream.getTracks().forEach(t=>t.stop());stream=null;$('video').hidden=true;let r=await fetch('https://world.openfoodfacts.org/api/v2/product/'+code+'.json'),j=await r.json();if(j.status===1){let p=j.product,n=p.nutriments||{};$('fname').value=p.product_name||'Scanned food';$('serving').value=p.serving_size||'100 g';$('fcal').value=Math.round(n['energy-kcal_serving']||n['energy-kcal_100g']||0);$('fp').value=n.proteins_serving??n.proteins_100g??0;$('fc').value=n.carbohydrates_serving??n.carbohydrates_100g??0;$('ff').value=n.fat_serving??n.fat_100g??0}else alert('Product not found; enter nutrition manually.')}else requestAnimationFrame(loop)};loop()}catch(e){alert(e.message)}};
